version: "3.9"

services:
  discount:
    image: hashorg/hash-mock-discount-service
    container_name: discount
    ports:
      - "50051:50051"
  api:
    container_name: checkout-api
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"